name: "setup-podman"

description: "Composite action to install and configure podman for use in GitHub Actions"

runs:
  using: "composite"
  steps:
    - name: Install podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman podman-compose
      shell: bash
      
    - name: Configure podman
      run: |
        # Enable cgroup v2 delegation for rootless podman
        sudo mkdir -p /etc/systemd/system/user@.service.d
        echo '[Service]
        Delegate=cpu cpuset io memory pids' | sudo tee /etc/systemd/system/user@.service.d/delegate.conf
        sudo systemctl daemon-reload
        
        # Set up subuid/subgid for rootless containers
        sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $USER
        
        # Configure containers
        mkdir -p ~/.config/containers
        echo 'unqualified-search-registries = ["docker.io"]' > ~/.config/containers/registries.conf
        echo '{"default":[{"type":"insecureAcceptAnything"}]}' > ~/.config/containers/policy.json
        
        # Start podman service
        systemctl --user start podman.socket || true
        
        # Test podman
        podman version
        podman info
      shell: bash 