// DO NOT MODIFY THIS FILE MANUALLY!
// This file is auto-generated by build.rs from permission_sets! macro invocations.
// To update: modify the source permission_sets! invocations and rebuild.
//
// This file is checked into version control to:
// 1. Make permission set changes visible in pull requests
// 2. Catch breaking changes to the permission set API
// 3. Ensure CI fails if the generated code is out of sync

#[derive(Clone, PartialEq, Eq, Copy, Debug, async_graphql::Enum)]
pub enum PermissionSetName {
    AccessViewer,
    AccessWriter,
    AccountingViewer,
    AccountingWriter,
    AuditViewer,
    CollectionPaymentDate,
    CollectionViewer,
    CollectionWriter,
    ContractCreation,
    CreditTermTemplatesViewer,
    CreditTermTemplatesWriter,
    CreditViewer,
    CreditWriter,
    CustodyViewer,
    CustodyWriter,
    CustomerViewer,
    CustomerWriter,
    DashboardViewer,
    DepositFreeze,
    DepositUnfreeze,
    DepositViewer,
    DepositWriter,
    ExposedConfigViewer,
    ExposedConfigWriter,
    GovernanceViewer,
    GovernanceWriter,
    ReportViewer,
    ReportWriter,
}

impl std::str::FromStr for PermissionSetName {
    type Err = strum::ParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s == core_access::PERMISSION_SET_ACCESS_VIEWER { return Ok(Self::AccessViewer); }
        if s == core_access::PERMISSION_SET_ACCESS_WRITER { return Ok(Self::AccessWriter); }
        if s == core_accounting::PERMISSION_SET_ACCOUNTING_VIEWER { return Ok(Self::AccountingViewer); }
        if s == core_accounting::PERMISSION_SET_ACCOUNTING_WRITER { return Ok(Self::AccountingWriter); }
        if s == crate::PERMISSION_SET_AUDIT_VIEWER { return Ok(Self::AuditViewer); }
        if s == core_credit_collection::PERMISSION_SET_COLLECTION_PAYMENT_DATE { return Ok(Self::CollectionPaymentDate); }
        if s == core_credit_collection::PERMISSION_SET_COLLECTION_VIEWER { return Ok(Self::CollectionViewer); }
        if s == core_credit_collection::PERMISSION_SET_COLLECTION_WRITER { return Ok(Self::CollectionWriter); }
        if s == contract_creation::PERMISSION_SET_CONTRACT_CREATION { return Ok(Self::ContractCreation); }
        if s == core_credit_terms::PERMISSION_SET_CREDIT_TERM_TEMPLATES_VIEWER { return Ok(Self::CreditTermTemplatesViewer); }
        if s == core_credit_terms::PERMISSION_SET_CREDIT_TERM_TEMPLATES_WRITER { return Ok(Self::CreditTermTemplatesWriter); }
        if s == core_credit::PERMISSION_SET_CREDIT_VIEWER { return Ok(Self::CreditViewer); }
        if s == core_credit::PERMISSION_SET_CREDIT_WRITER { return Ok(Self::CreditWriter); }
        if s == core_custody::PERMISSION_SET_CUSTODY_VIEWER { return Ok(Self::CustodyViewer); }
        if s == core_custody::PERMISSION_SET_CUSTODY_WRITER { return Ok(Self::CustodyWriter); }
        if s == core_customer::PERMISSION_SET_CUSTOMER_VIEWER { return Ok(Self::CustomerViewer); }
        if s == core_customer::PERMISSION_SET_CUSTOMER_WRITER { return Ok(Self::CustomerWriter); }
        if s == dashboard::PERMISSION_SET_DASHBOARD_VIEWER { return Ok(Self::DashboardViewer); }
        if s == core_deposit::PERMISSION_SET_DEPOSIT_FREEZE { return Ok(Self::DepositFreeze); }
        if s == core_deposit::PERMISSION_SET_DEPOSIT_UNFREEZE { return Ok(Self::DepositUnfreeze); }
        if s == core_deposit::PERMISSION_SET_DEPOSIT_VIEWER { return Ok(Self::DepositViewer); }
        if s == core_deposit::PERMISSION_SET_DEPOSIT_WRITER { return Ok(Self::DepositWriter); }
        if s == domain_config::PERMISSION_SET_EXPOSED_CONFIG_VIEWER { return Ok(Self::ExposedConfigViewer); }
        if s == domain_config::PERMISSION_SET_EXPOSED_CONFIG_WRITER { return Ok(Self::ExposedConfigWriter); }
        if s == governance::PERMISSION_SET_GOVERNANCE_VIEWER { return Ok(Self::GovernanceViewer); }
        if s == governance::PERMISSION_SET_GOVERNANCE_WRITER { return Ok(Self::GovernanceWriter); }
        if s == core_report::PERMISSION_SET_REPORT_VIEWER { return Ok(Self::ReportViewer); }
        if s == core_report::PERMISSION_SET_REPORT_WRITER { return Ok(Self::ReportWriter); }
        Err(strum::ParseError::VariantNotFound)
    }
}

impl std::fmt::Display for PermissionSetName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Self::AccessViewer => core_access::PERMISSION_SET_ACCESS_VIEWER,
            Self::AccessWriter => core_access::PERMISSION_SET_ACCESS_WRITER,
            Self::AccountingViewer => core_accounting::PERMISSION_SET_ACCOUNTING_VIEWER,
            Self::AccountingWriter => core_accounting::PERMISSION_SET_ACCOUNTING_WRITER,
            Self::AuditViewer => crate::PERMISSION_SET_AUDIT_VIEWER,
            Self::CollectionPaymentDate => core_credit_collection::PERMISSION_SET_COLLECTION_PAYMENT_DATE,
            Self::CollectionViewer => core_credit_collection::PERMISSION_SET_COLLECTION_VIEWER,
            Self::CollectionWriter => core_credit_collection::PERMISSION_SET_COLLECTION_WRITER,
            Self::ContractCreation => contract_creation::PERMISSION_SET_CONTRACT_CREATION,
            Self::CreditTermTemplatesViewer => core_credit_terms::PERMISSION_SET_CREDIT_TERM_TEMPLATES_VIEWER,
            Self::CreditTermTemplatesWriter => core_credit_terms::PERMISSION_SET_CREDIT_TERM_TEMPLATES_WRITER,
            Self::CreditViewer => core_credit::PERMISSION_SET_CREDIT_VIEWER,
            Self::CreditWriter => core_credit::PERMISSION_SET_CREDIT_WRITER,
            Self::CustodyViewer => core_custody::PERMISSION_SET_CUSTODY_VIEWER,
            Self::CustodyWriter => core_custody::PERMISSION_SET_CUSTODY_WRITER,
            Self::CustomerViewer => core_customer::PERMISSION_SET_CUSTOMER_VIEWER,
            Self::CustomerWriter => core_customer::PERMISSION_SET_CUSTOMER_WRITER,
            Self::DashboardViewer => dashboard::PERMISSION_SET_DASHBOARD_VIEWER,
            Self::DepositFreeze => core_deposit::PERMISSION_SET_DEPOSIT_FREEZE,
            Self::DepositUnfreeze => core_deposit::PERMISSION_SET_DEPOSIT_UNFREEZE,
            Self::DepositViewer => core_deposit::PERMISSION_SET_DEPOSIT_VIEWER,
            Self::DepositWriter => core_deposit::PERMISSION_SET_DEPOSIT_WRITER,
            Self::ExposedConfigViewer => domain_config::PERMISSION_SET_EXPOSED_CONFIG_VIEWER,
            Self::ExposedConfigWriter => domain_config::PERMISSION_SET_EXPOSED_CONFIG_WRITER,
            Self::GovernanceViewer => governance::PERMISSION_SET_GOVERNANCE_VIEWER,
            Self::GovernanceWriter => governance::PERMISSION_SET_GOVERNANCE_WRITER,
            Self::ReportViewer => core_report::PERMISSION_SET_REPORT_VIEWER,
            Self::ReportWriter => core_report::PERMISSION_SET_REPORT_WRITER,
        };
        write!(f, "{}", s)
    }
}
