mutation RecordPaymentTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "RECORD_PAYMENT"
      description: "Make payment for loan."
      params: [
        {
          name: "checkingAccount"
          type: UUID
          description: "User Checking account ID."
        }
        {
          name: "loanReceivableAccount"
          type: UUID
          description: "Loan amount or interest outstanding account ID."
        }
        {
          name: "paymentAmount"
          type: DECIMAL
          description: "Amount of USD being paid against outstanding amount."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.checkingAccount"
          units: "params.paymentAmount"
          currency: "'USD'"
          entryType: "'RECORD_PAYMENT_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.loanReceivableAccount"
          units: "params.paymentAmount"
          currency: "'USD'"
          entryType: "'RECORD_PAYMENT_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostRecordPaymentTransaction(
  $transactionId: UUID!
  $checkingAccount: UUID!
  $loanReceivableAccount: UUID!
  $paymentAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "RECORD_PAYMENT"
      params: {
        checkingAccount: $checkingAccount
        loanReceivableAccount: $loanReceivableAccount
        paymentAmount: $paymentAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
    }
  }
}
