mutation RecordPaymentTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "RECORD_PAYMENT"
      description: "Make payment for loan."
      params: [
        {
          name: "checkingAccount"
          type: UUID
          description: "User Checking account ID."
        }
        {
          name: "loanDisbursementsReceivableAccount"
          type: UUID
          description: "Loan disbursed amount outstanding account ID."
        }
        {
          name: "loanInterestReceivableAccount"
          type: UUID
          description: "Loan interest amount outstanding account ID."
        }
        {
          name: "disbursementsPaymentAmount"
          type: DECIMAL
          description: "Amount of USD being paid against outstanding disbursements amount."
        }
        {
          name: "interestPaymentAmount"
          type: DECIMAL
          description: "Amount of USD being paid against outstanding interest amount."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.checkingAccount"
          units: "params.disbursementsPaymentAmount + params.interestPaymentAmount"
          currency: "'USD'"
          entryType: "'RECORD_PAYMENT_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.loanDisbursementsReceivableAccount"
          units: "params.disbursementsPaymentAmount"
          currency: "'USD'"
          entryType: "'RECORD_DISBURSEMENTS_PAYMENT_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.loanInterestReceivableAccount"
          units: "params.interestPaymentAmount"
          currency: "'USD'"
          entryType: "'RECORD_INTEREST_PAYMENT_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostRecordPaymentTransaction(
  $transactionId: UUID!
  $checkingAccount: UUID!
  $loanDisbursementsReceivableAccount: UUID!
  $loanInterestReceivableAccount: UUID!
  $disbursementsPaymentAmount: Decimal!
  $interestPaymentAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "RECORD_PAYMENT"
      params: {
        checkingAccount: $checkingAccount
        loanDisbursementsReceivableAccount: $loanDisbursementsReceivableAccount
        loanInterestReceivableAccount: $loanInterestReceivableAccount
        disbursementsPaymentAmount: $disbursementsPaymentAmount
        interestPaymentAmount: $interestPaymentAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}
