# Linux-Docker or old Docker-Desktop need this extra_hosts entry.
# Podman and modern Desktop skip this file and work out of the box.
version: "3.9"

x-hostgw: &hostgw
  extra_hosts:
    - "host.containers.internal:host-gateway"

services:
  kratos-admin:
    <<: *hostgw

  kratos-customer:
    <<: *hostgw

  oathkeeper:
    <<: *hostgw
