FROM alpine:latest as base

RUN mkdir -p /lana && chown 1000:1000 /lana

FROM gcr.io/distroless/static

# Copy the pre-built binary from build context
COPY --chmod=0755 binaries/lana-cli /bin/lana-cli

COPY --from=base --chown=1000:1000 /lana /lana

USER 1000

ARG VERSION
ARG BUILDTIME
ARG COMMITHASH
ENV VERSION="$VERSION" \
    BUILDTIME="$BUILDTIME" \
    COMMITHASH="$COMMITHASH" \
    LANA_HOME=/lana

CMD ["lana-cli"]
