#@ load("@ytt:data", "data")

#@ load("fragments.lib.yml",
#@   "nix_flake_cachix_image_config",
#@   "next_version_task",
#@   "build_release",
#@   "check_latest_commit",
#@   "nix_build_and_cache",
#@   "set_pr_status"
#@ )

groups:
  - name: all
    jobs:
      - build-release-main
      - kickoff-pr
      - cache-lana-deps-pr
      - build-release-pr
  - name: main
    jobs:
      - build-release-main
  - name: pr
    jobs:
      - kickoff-pr
      - build-release-pr
      - cache-lana-deps-pr

jobs:
  - name: build-release-main
    serial: true
    plan:
    - get: repo
      trigger: true
    - #@ next_version_task()
    - #@ build_release()

  - name: kickoff-pr
    max_in_flight: 3
    plan:
    - get: prs
      trigger: true
      version: every

  - name: cache-lana-deps-pr
    max_in_flight: 3
    plan:
    - get: prs
      trigger: true
      version: every
      passed:
      - kickoff-pr

  - name: build-release-pr
    plan:
    - get: prs
      trigger: true
      version: every
      passed:
      - cache-lana-deps-pr
      params:
        fetch_tags: true
    - #@ next_version_task("prs")
    - #@ build_release("prs")

resources:
  - name: repo
    type: git
    source:
      ignore_paths:
        - "ci/*[^md]"
      fetch_tags: true
      uri: #@ data.values.git_uri
      branch: #@ data.values.git_branch
      private_key: #@ data.values.github_private_key
    webhook_token: ((webhook.secret))

  - name: prs
    type: pull-request
    check_every: 24h
    webhook_token: ((webhook.secret))
    source:
      base_branch: #@ data.values.git_branch
      repository: #@ data.values.gh_org + "/" + data.values.gh_repository
      access_token: #@ data.values.github_token

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
