#@ load("@ytt:data", "data")

#@ load("fragments.lib.yml",
#@   "nix_flake_cachix_image_config",
#@   "next_version_task",
#@   "build_release",
#@   "check_latest_commit",
#@   "nix_build_and_cache",
#@   "exec_phase",
#@   "set_pr_status"
#@ )

groups:
  - name: all
    jobs:
      - build-release-main
      - kickoff-pr
      - populate-nix-cache-pr
  - name: main
    jobs:
      - build-release-main
  - name: pr
    jobs:
      - kickoff-pr
      - populate-nix-cache-pr

jobs:
  - name: build-release-main
    serial: true
    plan:
    - get: repo
      trigger: true
    - #@ next_version_task()
    - #@ build_release()

  - name: kickoff-pr
    max_in_flight: 3
    plan:
    - get: prs
      trigger: true
      version: every
    - in_parallel:
      - #@ set_pr_status("Awaiting build slot") 
      - task: cache-dev-profile
        config:
          platform: linux
          image_resource: #@ nix_flake_cachix_image_config()
          inputs:
          - name: prs
            path: repo
          params:
            CACHIX_AUTH_TOKEN: #@ data.values.cachix_auth_token
            CACHIX_CACHE_NAME: #@ data.values.cachix_cache_name
          run:
            path: sh
            args:
              - -exc
              - |
                set -euo pipefail
                cd repo
                cachix use $CACHIX_CACHE_NAME
                cachix watch-exec ${CACHIX_CACHE_NAME} -- nix develop --profile /tmp/dev-profile --command true

  - name: populate-nix-cache-pr
    max_in_flight: 3
    plan:
    - get: prs
      trigger: true
      version: every
    - #@ exec_phase(["lana-deps"])
    - #@ exec_phase(["lana-cli-debug", "bats"])

resources:
  - name: repo
    type: git
    source:
      ignore_paths:
        - "ci/*[^md]"
      fetch_tags: true
      uri: #@ data.values.git_uri
      branch: #@ data.values.git_branch
      private_key: #@ data.values.github_private_key
    webhook_token: ((webhook.secret))

  - name: prs
    type: pull-request
    check_every: 24h
    webhook_token: ((webhook.secret))
    source:
      base_branch: #@ data.values.git_branch
      repository: #@ data.values.gh_org + "/" + data.values.gh_repository
      access_token: #@ data.values.github_token

  - name: prs-out
    type: pull-request
    check_every: 24h
    webhook_token: ((webhook.secret))
    source:
      base_branch: #@ data.values.git_branch
      repository: #@ data.values.gh_org + "/" + data.values.gh_repository
      access_token: #@ data.values.github_token

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: cfcommunity/github-pr-resource
