[package]
name = "entity-rollups"
version = "0.3.649-dev"
license = "FSL-1.1-ALv2"
edition = "2024"

[features]
fail-on-warnings = []

[[bin]]
name = "entity-rollups"
path = "src/main.rs"

[dependencies]
core-access = { path = "../../core/access", features = ["json-schema"] }
governance = { path = "../../core/governance", features = ["json-schema"] }

clap = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
colored = "2.0"
similar = { version = "2.6", features = ["inline"] }

[dev-dependencies]
tempfile = "3.13.0"
