[package]
name = "core-user"
version = "0.2.9-dev"
edition = "2021"

[features]

fail-on-warnings = []
graphql = ["shared-primitives/graphql", "es-entity/graphql"]

[dependencies]
shared-primitives = { path = "../shared-primitives" }

audit = { path = "../../lib/audit" }
authz = { path = "../../lib/authz" }
outbox = { path = "../../lib/outbox" }
es-entity = { path = "../../lib/es-entity" }

strum = { workspace = true }
serde = { workspace = true }
derive_builder = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
