/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Credit",
      link: {
        type: "doc",
        id: "credit/index",
      },
      items: [
        "credit/facility",
        "credit/disbursal",
        "credit/obligation",
        "credit/payment",
        "credit/terms",
        "credit/interest-process",
      ],
    },
    {
      type: "category",
      label: "Accounting",
      link: {
        type: "doc",
        id: "accounting/index",
      },
      items: ["accounting/closing", "accounting/fiscal-year"],
    },
    {
      type: "category",
      label: "ERDs",
      link: {
        type: "doc",
        id: "erds/index",
      },
      items: ["erds/cala", "erds/lana"],
    },
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: [
        {
          type: "category",
          label: "Admin API",
          link: {
            type: "doc",
            id: "api/admin/generated",
          },
          items: [
            {
              type: "category",
              label: "Operations",
              key: "admin-operations-group",
              items: [
                {
                  type: "autogenerated",
                  dirName: "api/admin/operations",
                },
              ],
            },
            {
              type: "category",
              label: "Types",
              key: "admin-types-group",
              items: [
                {
                  type: "autogenerated",
                  dirName: "api/admin/types",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Customer API",
          link: {
            type: "doc",
            id: "api/customer/generated",
          },
          items: [
            {
              type: "category",
              label: "Operations",
              key: "customer-operations-group",
              items: [
                {
                  type: "autogenerated",
                  dirName: "api/customer/operations",
                },
              ],
            },
            {
              type: "category",
              label: "Types",
              key: "customer-types-group",
              items: [
                {
                  type: "autogenerated",
                  dirName: "api/customer/types",
                },
              ],
            },
          ],
        },
        "api/events",
      ],
    },
  ],
};

export default sidebars;
