/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "doc",
        id: "getting-started/index",
      },
      items: [],
    },
    {
      type: "category",
      label: "For Developers",
      link: {
        type: "doc",
        id: "for-developers/index",
      },
      items: [
        "for-developers/quickstart",
        "for-developers/authentication",
        "for-developers/webhooks",
        {
          type: "category",
          label: "Admin API",
          link: {
            type: "doc",
            id: "for-developers/admin-api/generated",
          },
          items: [
            {
              type: "category",
              label: "Operations",
              key: "admin-operations-group",
              items: [
                {
                  type: "autogenerated",
                  dirName: "for-developers/admin-api/operations",
                },
              ],
            },
            {
              type: "category",
              label: "Types",
              key: "admin-types-group",
              items: [
                {
                  type: "autogenerated",
                  dirName: "for-developers/admin-api/types",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Customer API",
          link: {
            type: "doc",
            id: "for-developers/customer-api/generated",
          },
          items: [
            {
              type: "category",
              label: "Operations",
              key: "customer-operations-group",
              items: [
                {
                  type: "autogenerated",
                  dirName: "for-developers/customer-api/operations",
                },
              ],
            },
            {
              type: "category",
              label: "Types",
              key: "customer-types-group",
              items: [
                {
                  type: "autogenerated",
                  dirName: "for-developers/customer-api/types",
                },
              ],
            },
          ],
        },
        "for-developers/events/events",
      ],
    },
    {
      type: "category",
      label: "For Operators",
      link: {
        type: "doc",
        id: "for-operators/index",
      },
      items: [
        {
          type: "category",
          label: "Credit Management",
          link: {
            type: "doc",
            id: "for-operators/credit/index",
          },
          items: [
            "for-operators/credit/facility",
            "for-operators/credit/disbursal",
            "for-operators/credit/obligation",
            "for-operators/credit/payment",
            "for-operators/credit/terms",
            "for-operators/credit/interest-process",
          ],
        },
        {
          type: "category",
          label: "Accounting",
          link: {
            type: "doc",
            id: "for-operators/accounting/index",
          },
          items: [
            "for-operators/accounting/closing",
            "for-operators/accounting/fiscal-year",
          ],
        },
        {
          type: "category",
          label: "Configuration",
          link: {
            type: "doc",
            id: "for-operators/configuration/index",
          },
          items: [],
        },
      ],
    },
    {
      type: "category",
      label: "For Architects",
      link: {
        type: "doc",
        id: "for-architects/index",
      },
      items: [
        "for-architects/functional-architecture",
        {
          type: "category",
          label: "Data Models (ERDs)",
          link: {
            type: "doc",
            id: "for-architects/erds/index",
          },
          items: [
            "for-architects/erds/cala",
            "for-architects/erds/lana",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      items: [
        "reference/glossary",
        "reference/changelog",
      ],
    },
  ],
};

export default sidebars;
