version: 1
default_environment: dev
project_id: 608399cc-8e94-418f-a5ff-bdad5cb5a190
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-postgres
        config:
          host: core-pg
          user: user
          database: pg
          password: password
      - name: tap-sumsubapi
        config:
          host: core-pg
          user: user
          database: pg
          password: password
- name: staging
- name: prod
jobs:
- name: tap-postgres-to-target-bigquery-run-dbt
  tasks:
  - tap-postgres target-bigquery dbt-bigquery:run
- name: test-dbt
  tasks:
  - dbt-bigquery:test
- name: poll-bitfinex
  tasks:
  - tap-bitfinexapi target-bigquery
- name: sync-sumsub
  tasks:
  - tap-sumsubapi target-bigquery
schedules:
- name: postgres-to-bigquery-dbt
  interval: '*/5 * * * *'
  job: tap-postgres-to-target-bigquery-run-dbt
- name: poll-bitfinex-on-minute
  interval: '* * * * *'
  job: poll-bitfinex
- name: sync-sumsub-hourly
  interval: '@hourly'
  job: sync-sumsub
- name: test-dbt-daily
  interval: '@daily'
  job: test-dbt
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      json_as_object: true
      flattening_enabled: true
      flattening_max_depth: 10
    select:
    - public-*.*
  - name: tap-bitfinexapi
    namespace: tap_bitfinexapi
    pip_url: -e extract/tap-bitfinexapi
    executable: tap-bitfinexapi
  - name: tap-sumsubapi
    namespace: tap_sumsubapi
    pip_url: -e extract/tap-sumsubapi
    executable: tap-sumsubapi
    settings:
    - name: host
    - name: user
    - name: database
    - name: password
    - name: key
    - name: secret
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      project: lana-dev-440721
      generate_view: true
  - name: target-snowflake
    variant: meltanolabs
    pip_url: meltanolabs-target-snowflake
    config:
      account: cdagppu-sy37948
      database: MELTANO_DATABASE
      user: MELTANO_USER
      role: MELTANO_ROLE
      warehouse: MELTANO_WAREHOUSE
      schema: RAW_SCHEMA
      default_target_schema: RAW_SCHEMA
      flattening_enabled: true
      flattening_max_depth: 10
  transformers:
  - name: dbt-bigquery
    variant: dbt-labs
    pip_url: dbt-core~=1.3.0 dbt-bigquery~=1.3.0
    config:
      auth_method: service-account
      project: lana-dev-440721
  utilities:
  - name: sqlfluff
    variant: sqlfluff
    pip_url: sqlfluff sqlfluff-templater-dbt dbt-core dbt-bigquery
    settings:
    - name: dataset
      env: DBT_BIGQUERY_DATASET
    - name: keyfile
      env: DBT_BIGQUERY_KEYFILE
    - name: auth_method
      env: DBT_BIGQUERY_AUTH_METHOD
      value: service-account
    - name: project
      env: DBT_BIGQUERY_PROJECT
      value: lana-dev-440721
  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.8.1
      --constraint
      https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
