version: 1
default_environment: dev
project_id: 608399cc-8e94-418f-a5ff-bdad5cb5a190
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-postgres
        config:
          host: localhost
          port: 5433
          user: user
          database: pg
          password: password
      - name: tap-sumsubapi
        config:
          host: localhost
          port: 5433
          user: user
          database: pg
          password: password
- name: staging
- name: prod
jobs:
- name: tap-postgres-to-target-bigquery-run-dbt
  tasks:
  - tap-postgres target-bigquery dbt-bigquery:run
- name: test-dbt
  tasks:
  - dbt-bigquery:test
- name: poll-bitfinex
  tasks:
  - tap-bitfinexapi target-bigquery
- name: sync-sumsub
  tasks:
  - tap-sumsubapi target-bigquery
- name: drop-old-relations
  tasks:
  - dbt-bigquery:drop-old-relations
- name: transpile_and_run_duckdb
  tasks:
  - wiper:all
  - tap-postgres target-duckdb
  - dbt-bigquery:compile
  - sqlglot-transpile:transpile
  - dbt-duckdb:run
- name: transpile_and_run_duckdb_debug
  tasks:
  - wiper:all
  - tap-postgres target-duckdb
  - dbt-bigquery:compile-sub-model
  - sqlglot-transpile:transpile
  - dbt-duckdb:run
schedules:
- name: postgres-to-bigquery-dbt
  interval: '*/10 * * * *'
  job: tap-postgres-to-target-bigquery-run-dbt
- name: poll-bitfinex-on-minute
  interval: '* * * * *'
  job: poll-bitfinex
- name: sync-sumsub-on-minute
  interval: '*/10 * * * *'
  job: sync-sumsub
- name: test-dbt-daily
  interval: '@daily'
  job: test-dbt
- name: drop-old-relations-weekly
  interval: '@weekly'
  job: drop-old-relations
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      json_as_object: true
      flattening_enabled: true
      flattening_max_depth: 10
    select:
    - public-*.*
  - name: tap-bitfinexapi
    namespace: tap_bitfinexapi
    pip_url: -e extract/tap-bitfinexapi
    executable: tap-bitfinexapi
  - name: tap-sumsubapi
    namespace: tap_sumsubapi
    pip_url: -e extract/tap-sumsubapi
    executable: tap-sumsubapi
    settings:
    - name: host
    - name: user
    - name: database
    - name: password
    - name: key
    - name: secret
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      project: lana-dev-440721
      generate_view: true
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.8
    config:
      default_target_schema: lana
      path: ${MELTANO_PROJECT_ROOT}/.build/target_duckdb.db
      primary_key_required: false
      add_metadata_columns: true
  transformers:
  - name: dbt-bigquery
    variant: dbt-labs
    pip_url: dbt-core==1.9.0 dbt-bigquery==1.9.0 python-dateutil==2.8.2 six==1.16.0
    commands:
      drop-old-relations: run-operation drop_old_relations
      compile-sub-model:
        args: compile --models stg_credit_facility_events stg_core_chart_events
    config:
      auth_method: service-account
      project: lana-dev-440721
      dataset: lana_dataset
      keyfile: /Users/n/Code/lana-bank/meltano/keyfile.json
  utilities:
  - name: sqlfluff
    variant: sqlfluff
    pip_url: sqlfluff sqlfluff-templater-dbt dbt-core dbt-bigquery
    settings:
    - name: dataset
      env: DBT_BIGQUERY_DATASET
    - name: keyfile
      env: DBT_BIGQUERY_KEYFILE
    - name: auth_method
      env: DBT_BIGQUERY_AUTH_METHOD
      value: service-account
    - name: project
      env: DBT_BIGQUERY_PROJECT
      value: lana-dev-440721
  - name: airflow
    variant: apache
    pip_url: >
      git+https://github.com/meltano/airflow-ext.git@main
      apache-airflow==2.9.1
      --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.9.1/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
  - name: sqlglot-transpile
    namespace: sqlglot_transpile
    pip_url: sqlglot==26.16.2
    executable: python
    commands:
      transpile:
        args: >
          "${MELTANO_PROJECT_ROOT}/scripts/transpile_sql.py"
          "${MELTANO_PROJECT_ROOT}/transform/target/compiled/lana/models"
          -o "${MELTANO_PROJECT_ROOT}/transform_duckdb/models"
          --exclusions-file scripts/sqlglot_exclusions.txt
          --debug
        description: Transpile compiled dbt SQL from BigQuery → DuckDB/Snowflake
  - name: wiper
    namespace: custom_ops
    executable: rm
    commands:
      all:
        args: -rf ${MELTANO_PROJECT_ROOT}/.build/target_duckdb.db ${MELTANO_PROJECT_ROOT}/transform_duckdb/models ${MELTANO_PROJECT_ROOT}/transform_duckdb/target/ ${MELTANO_PROJECT_ROOT}/transform/target/
        description: "Delete the local DuckDB file before re-loading"
  - name: dbt-duckdb
    namespace: dbt_duckdb
    pip_url: dbt-core==1.9.0 dbt-duckdb==1.9.1
    executable: dbt
    settings:
    - name: profiles_dir
      env: DBT_PROFILES_DIR
      value: ${MELTANO_PROJECT_ROOT}/transform/profiles/duckdb
    - name: project_dir
      env: DBT_PROJECT_DIR
      value: ${MELTANO_PROJECT_ROOT}/transform_duckdb
    commands:
      run:
        args: run
        description: Compile SQL and execute against DuckDB
      debug:
        args: debug
        description: Test connection to DuckDB
