[package]
name = "lana-ids"
version = "0.3.558-dev"
license = "FSL-1.1-ALv2"
edition = "2021"

[features]

default = ["graphql"]
graphql = []

[dependencies]
governance = { path = "../../core/governance", features = ["graphql"] }

job = { path = "../../lib/job" }

es-entity = { workspace = true, features = ["graphql"] }
cala-ledger = { workspace = true }
