name: lana
version: '1.0'
profile: meltano
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
model-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
log-path: logs
packages-install-path: dbt_packages
clean-targets:
- dbt_packages
- logs
models:
  lana: null
tests:
  schema: null
  store_failures: true
on-run-start:
- '{{create_udfs()}}'
on-run-end:
- '{{create_data_test_results()}}'
vars:
  sats_per_bitcoin: '100000000'
  deposits_coverage_limit: '10289.00'
