mutation DagsterLanaPipelineTrigger {
  launchRun(executionParams: {
    selector: {
      jobName: "PIPELINE_JOB_NAME_PLACEHOLDER"
      repositoryLocationName: "Lana Pipelines"
      repositoryName: "__repository__"
    }
  }) {
    __typename
    ... on LaunchRunSuccess {
      run {
        id
        runId
        status
      }
    }
    ... on PythonError {
      message
    }
  }
}