version: 2

sources:
  - name: lana
    dataset: "{{ env_var('TARGET_BIGQUERY_DATASET', '') }}"
    tables:
      - name: public_cala_balance_history_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_accounts_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_account_sets_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_account_set_member_accounts_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_account_set_member_account_sets_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_chart_events_view

      - name: public_core_chart_node_events_view

      - name: public_core_collateral_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_credit_facility_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_credit_facility_repayment_plans_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_deposit_accounts_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_deposit_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_disbursal_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_interest_accrual_cycle_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_obligation_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_obligation_installment_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_payment_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_withdrawal_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_withdrawals_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_customer_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: bitfinex_ticker_view
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day

      - name: bitfinex_trades_view
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day

      - name: bitfinex_order_book_view
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day

      - name: sumsub_applicants_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_user_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_role_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_permission_set_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_approval_process_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_committee_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_policy_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_customer_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_deposit_account_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_deposit_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_withdrawal_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_custodian_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_collateral_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_credit_facility_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_disbursal_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_interest_accrual_cycle_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_obligation_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_obligation_installment_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_payment_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_terms_template_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_chart_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_chart_node_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_manual_transaction_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_document_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_liquidation_process_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day
