version: 2

sources:
  - name: lana
    dataset: "{{ env_var('TARGET_BIGQUERY_DATASET', '') }}"
    tables:

      - name: public_cala_balance_history_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_accounts_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_account_sets_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_account_set_member_accounts_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_account_set_member_account_sets_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_credit_facility_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: ticker_view
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day
