version: 2

sources:
  - name: lana
    tables:
      - name: public_cala_balance_history_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_accounts_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_account_sets_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_account_set_member_accounts_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_cala_account_set_member_account_sets_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_chart_events_view

      - name: public_core_collateral_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_credit_facility_events_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_credit_facility_repayment_plans_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_deposit_accounts_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_deposit_events_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_disbursal_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_interest_accrual_cycle_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_obligation_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_payment_allocation_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_payment_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_withdrawal_events_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_withdrawals_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_customer_events_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: bitfinex_ticker_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day

      - name: bitfinex_trades_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day

      - name: bitfinex_order_book_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day

      - name: sumsub_applicants_view
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day
