version: 2

sources:
  - name: lana
    schema: RAW_SCHEMA
    tables:

      - name: cala_balance_history
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: cala_accounts
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: cala_account_sets
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: cala_account_set_member_accounts
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: cala_account_set_member_account_sets
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: credit_facility_events
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: customer_events
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: bitfinex_ticker
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day

      - name: bitfinex_trades
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day

      - name: bitfinex_order_book
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 1
            period: day

      - name: sumsub_applicants
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day
