
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_lana_dw'
version: '1.0.0'

# UDFs are created once at Dagster startup (see resources/dbt.py)
# on-run-start:
# - '{{create_udfs()}}'

vars:
  sats_per_bitcoin: '100000000'
  cents_per_usd: '100'
  deposits_coverage_limit: '10289.00'

flags:
  send_anonymous_usage_stats: False
  use_colors: True
# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_lana_dw'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_lana_dw:
    # Config indicated by + and applies to all files under models/example/
    # example:
    #   +materialized: view

# Seed configurations for static data tables
seeds:
  dbt_lana_dw:
    +quote_columns: true
    "el-salvador-ssf":
      static_ncb_022_porcentaje_reservas_saneamiento:
        +column_types:
          category: STRING
          reserve_percentage: BIGNUMERIC
          consumer_calendar_ge_days: INT64
          consumer_calendar_le_days: INT64
      static_npb4_17_31_codigos_de_paises_o_territorios:
        +column_types:
          code: INT64
          nationality: STRING
          country: STRING
          iso_alpha_3_code: STRING
      static_nrp_41_estados_del_prestamo:
        +column_types:
          estado: STRING
          "explicación": STRING
          status: STRING
          explanation: STRING
          consumer_calendar_ge_days: INT64
          consumer_calendar_le_days: INT64
      "ncf_01":
        static_ncf_01_01_account_config_seed:
          +column_types:
            order_by: INT64
            title: STRING
            eng_title: STRING
            source_account_codes: STRING
        static_ncf_01_02_account_config_seed:
          +column_types:
            order_by: INT64
            title: STRING
            eng_title: STRING
            source_account_spaced_codes: STRING
        static_ncf_01_03_column_config_seed:
          +column_types:
            column_order_by: INT64
            column_title: STRING
            eng_column_title: STRING
        static_ncf_01_03_row_titles_seed:
          +column_types:
            order_by: INT64
            title: STRING
            eng_title: STRING
            source_account_codes: STRING
        static_ncf_01_04_account_config_seed:
          +column_types:
            order_by: INT64
            title: STRING
            eng_title: STRING
            source_account_codes: STRING
        static_nrp_28_01_account_config_seed:
          +column_types:
            order_by: INT64
            title: STRING
            eng_title: STRING
            sum_account_codes: STRING
            diff_account_codes: STRING
        static_nrp_28_01_liquidity_coefficients:
          +column_types:
            account_code: STRING
            account_name: STRING
            eng_account_name: STRING
            coefficient: BIGNUMERIC
