query($assetKey: AssetKeyInput!) {
  assetNodes(assetKeys: [$assetKey]) {
    id
    assetKey {
      path
    }
    dependencies {
      asset {
        assetKey {
          path
        }
      }
    }
  }
}

