name: "Cache Rust Dependencies"
description: "Restores and saves Cargo registry, git sources, and target directory."

runs:
  using: "composite"
  steps:
    - name: Cache Cargo registry and builds
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-gha-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-gha- 