version: 2

sources:
  - name: lana
    dataset: "{{ env_var('TARGET_BIGQUERY_DATASET', '') }}"
    tables:
      - name: core_withdrawal_events_rollup
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: core_deposit_events_rollup
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: core_deposit_account_events_rollup
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: core_public_ids
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day
