version: 2

sources:
  - name: lana
    dataset: "{{ env_var('TARGET_BIGQUERY_DATASET', '') }}"
    tables:
      - name: public_core_withdrawal_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_deposit_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_deposit_account_events_rollup_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

      - name: public_core_public_ids_view
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day
