select
    cast(null as string) as liquidation_id,
    cast(null as int64) as version,
    cast(null as timestamp) as created_at,
    cast(null as timestamp) as modified_at,
    cast(null as string) as credit_facility_id,
    cast(null as int64) as current_price,
    cast(null as int64) as expected_to_receive,
    cast(null as int64) as initially_estimated_to_liquidate,
    cast(null as int64) as initially_expected_to_receive,
    cast(null as int64) as outstanding,
    cast(null as string) as payment_id,
    cast(null as int64) as to_liquidate_at_current_price,
    cast(null as int64) as trigger_price,
    cast(null as boolean) as is_completed,
    cast(null as timestamp) as loaded_to_dw_at
