FROM python:3.13-slim

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dagster-dlt \
    dlt[bigquery] \
    dagster-dbt \
    dbt-bigquery


COPY generate-es-reports/ /opt/generate-es-reports

RUN pip install /opt/generate-es-reports

WORKDIR /opt/dagster/app

COPY src/ /opt/dagster/app

ENV SECRETS_FOLDER=/opt/dagster/secrets/

RUN mkdir -p $SECRETS_FOLDER

COPY keyfile.json $SECRETS_FOLDER

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "lana_pipelines/definitions.py"]