FROM python:3.13-slim

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dagster-dlt \
    dlt[bigquery] \
    dagster-dbt \
    dbt-bigquery

WORKDIR /opt/dagster/app

COPY src/ /opt/dagster/app

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "lana_pipelines/definitions.py"]