apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lanaBank.adminPanel.fullname" . }}
  labels:
    app: {{ template "lanaBank.adminPanel.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    kube-monkey/identifier: {{ template "lanaBank.adminPanel.fullname" . }}
    kube-monkey/enabled: enabled
    kube-monkey/kill-mode: fixed
    kube-monkey/kill-value: "1"
    kube-monkey/mtbf: "3"
spec:
  selector:
    matchLabels:
      app: {{ template "lanaBank.adminPanel.fullname" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.lanaBank.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "lanaBank.adminPanel.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        kube-monkey/identifier: {{ template "lanaBank.adminPanel.fullname" . }}
        kube-monkey/enabled: enabled
      {{- with .Values.lanaBank.labels }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ template "lanaBank.adminPanel.fullname" . }}
        image: "{{ .Values.lanaBank.adminPanel.image.repository }}@{{ .Values.lanaBank.adminPanel.image.digest }}"
        ports:
        - name: public
          containerPort: {{ .Values.lanaBank.adminPanel.service.port }}
          protocol: TCP
        env:
        - name: NEXT_PUBLIC_CORE_ADMIN_URL
          value: {{ .Values.lanaBank.adminPanel.coreAdminUrl }}
        - name: USER_ALLOWED_CALLBACK_URL
          value: {{ .Values.lanaBank.adminPanel.userAllowedCallbackUrl }}
        - name: JWKS_URL
          value: {{ .Values.lanaBank.jwksUrl }}
        - name: NEXT_PUBLIC_BASE_PATH
          value: /
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "lanaBank.fullname" . }}
              key: next-auth-secret
        - name: NEXTAUTH_URL
          value: {{ .Values.lanaBank.adminPanel.nextAuthUrl }}
        - name: NEXTAUTH_INTERNAL_URL
          value: {{ .Values.lanaBank.adminPanel.nextAuthInternalUrl }}
        - name: NEXT_AUTH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "lanaBank.fullname" . }}
              key: next-auth-admin-pg-con
        - name: EMAIL_SERVER
          valueFrom:
            secretKeyRef:
              name: {{ template "lanaBank.fullname" . }}
              key: smtp-uri
        - name: EMAIL_FROM
          value: {{ .Values.lanaBank.adminPanel.emailFrom }}
        startupProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.lanaBank.adminPanel.service.port }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.lanaBank.adminPanel.service.port }}
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
