apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lanaBank.fullname" . }}-config
data:
  lana.yml: |-
    app:
      job_execution:
        poll_interval: {{ .Values.lanaBank.app.jobExecution.pollInterval }}
      ledger:
        cala_url: {{ .Values.lanaBank.app.ledger.calaUrl }}
      user:
        superuser_email: {{ .Values.lanaBank.app.user.superuserEmail }}
      customer:
        kratos:
          admin_url: {{ .Values.lanaBank.app.customer.kratos.adminUrl }}
      service_account:
        gcp_location: {{ .Values.lanaBank.app.serviceAccount.gcpLocation }}
      storage:
        bucket_name: {{ .Values.lanaBank.app.storage.bucketName }}
        root_folder: {{ .Values.lanaBank.app.storage.rootFolder }}
      report:
        download_link_duration: 600
        dataform_repo: {{ .Values.lanaBank.app.report.dataformRepo }}
        dataform_output_dataset: {{ .Values.lanaBank.app.report.dataformOutputDataset }}
        dataform_release_config: {{ .Values.lanaBank.app.report.dataformReleaseConfig }}
    db:
      pool_size: {{ .Values.lanaBank.db.poolSize }}
    tracing:
      service_name: {{ .Values.lanaBank.tracing.serviceName }}
    public_server:
      jwks_url: {{ .Values.lanaBank.jwksUrl }}
    admin_server:
      jwks_url: {{ .Values.lanaBank.jwksUrl }}
