apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lanaBank.customerPortal.fullname" . }}
  labels:
    app: {{ template "lanaBank.customerPortal.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    kube-monkey/identifier: {{ template "lanaBank.customerPortal.fullname" . }}
    kube-monkey/enabled: enabled
    kube-monkey/kill-mode: fixed
    kube-monkey/kill-value: "1"
    kube-monkey/mtbf: "3"
spec:
  selector:
    matchLabels:
      app: {{ template "lanaBank.customerPortal.fullname" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.lanaBank.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "lanaBank.customerPortal.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        kube-monkey/identifier: {{ template "lanaBank.customerPortal.fullname" . }}
        kube-monkey/enabled: enabled
      {{- with .Values.lanaBank.labels }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ template "lanaBank.customerPortal.fullname" . }}
        image: "{{ .Values.lanaBank.customerPortal.image.repository }}@{{ .Values.lanaBank.customerPortal.image.digest }}"
        ports:
        - name: public
          containerPort: {{ .Values.lanaBank.customerPortal.service.port }}
          protocol: TCP
        env:
        - name: NEXT_PUBLIC_CORE_URL
          value: {{ .Values.lanaBank.customerPortal.corePublicUrl }}
        - name: NEXT_PUBLIC_KRATOS_PUBLIC_API
          value: {{ .Values.lanaBank.customerPortal.kratosPublicUrl }}
        - name: KRATOS_ADMIN_API
          value: {{ .Values.lanaBank.customerPortal.kratosAdminUrl }}
        - name: JWKS_URL
          value: {{ .Values.lanaBank.jwksUrl }}
        startupProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.lanaBank.customerPortal.service.port }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.lanaBank.customerPortal.service.port }}
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
