{{- if .Values.lanaBank.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lanaBank.fullname" . }}
  labels:
    app: {{ include "lanaBank.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, Set-Cookie"
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Original-URL $request_uri;
      proxy_set_header X-Forwarded-Method $request_method;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Uri $request_uri;
    nginx.ingress.kubernetes.io/auth-url: "http://lana-bank-oathkeeper-api.{{ .Release.Namespace }}.svc.cluster.local:4456/decisions"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.lanaBank.ingress.customerPortalHost }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "lanaBank.customerPortal.fullname" . }}
                port:
                  number: {{ $.Values.lanaBank.customerPortal.service.port }}
          - path: /graphql
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "lanaBank.public.fullname" . }}
                port:
                  number: {{ $.Values.lanaBank.server.public.port }}
          - path: /(?:self-service|sessions)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-kratos-public
                port:
                  number: 80
  tls:
    - hosts:
      - {{ .Values.lanaBank.ingress.customerPortalHost }}
      secretName: {{ printf "%s-tls" .Values.lanaBank.ingress.customerPortalHost }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lanaBank.fullname" . }}-admin
  labels:
    app: {{ include "lanaBank.fullname" . }}-admin
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, Set-Cookie"
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Original-URL $request_uri;
      proxy_set_header X-Forwarded-Method $request_method;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Uri $request_uri;
    nginx.ingress.kubernetes.io/auth-url: "http://lana-bank-oathkeeper-api.{{ .Release.Namespace }}.svc.cluster.local:4456/decisions"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.lanaBank.ingress.adminPanelHost }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "lanaBank.adminPanel.fullname" . }}
                port:
                  number: {{ $.Values.lanaBank.adminPanel.service.port }}
          - path: /graphql
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "lanaBank.admin.fullname" . }}
                port:
                  number: {{ $.Values.lanaBank.server.admin.port }}
          - path: /sumsub/callback
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "lanaBank.admin.fullname" . }}
                port:
                  number: {{ $.Values.lanaBank.server.admin.port }}
  tls:
    - hosts:
      - {{ .Values.lanaBank.ingress.adminPanelHost }}
      secretName: {{ printf "%s-tls" .Values.lanaBank.ingress.adminPanelHost }}
{{- end }}
