{{- if .Values.lanaBank.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lanaBank.fullname" . }}
  labels:
    app: {{ template "lanaBank.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  {{- if .Values.lanaBank.secrets.annotations }}
  annotations:
{{ toYaml .Values.lanaBank.secrets.annotations | indent 4 }}
  {{- end }}
type: Opaque
data:
  bq-service-account-base64: {{ .Values.lanaBank.secrets.bqServiceAccountBase64 | trim | b64enc | trim }}
  pg-con: {{ .Values.lanaBank.secrets.pgCon | trim | b64enc | trim }}
  next-auth-secret: {{ .Values.lanaBank.secrets.nextAuthSecret | b64enc | quote }}
  next-auth-admin-pg-con: {{ .Values.lanaBank.secrets.nextAuthAdminPgCon | trim | b64enc | trim }}
  smtp-uri: {{ .Values.lanaBank.secrets.smtpUri | trim | b64enc | trim }}
  sumsub-key: {{ .Values.lanaBank.secrets.sumsubKey | trim | b64enc | trim }}
  sumsub-secret: {{ .Values.lanaBank.secrets.sumsubSecret | trim | b64enc | trim }}
{{- end }}
