// @generated - do not edit. Run `make generate-entity-keys` to regenerate.

export const entityKeyFields: Record<string, readonly string[]> = {
  AccountingCsvDocument: ["accountingCsvDocumentId"],
  ApprovalProcess: ["approvalProcessId"],
  AuditEntry: ["auditEntryId"],
  ChartOfAccounts: ["chartOfAccountsId"],
  Collateral: ["collateralId"],
  Committee: ["committeeId"],
  CreditFacility: ["creditFacilityId"],
  CreditFacilityDisbursal: ["creditFacilityDisbursalId"],
  CreditFacilityPaymentAllocation: ["creditFacilityPaymentAllocationId"],
  CreditFacilityProposal: ["creditFacilityProposalId"],
  Custodian: ["custodianId"],
  Customer: ["customerId"],
  CustomerDocument: ["customerDocumentId"],
  Deposit: ["depositId"],
  DepositAccount: ["depositAccountId"],
  DomainConfig: ["domainConfigId"],
  FiscalYear: ["fiscalYearId"],
  JournalEntry: ["journalEntryId"],
  LedgerAccount: ["ledgerAccountId"],
  LedgerTransaction: ["ledgerTransactionId"],
  Liquidation: ["liquidationId"],
  LoanAgreement: ["loanAgreementId"],
  PendingCreditFacility: ["pendingCreditFacilityId"],
  PermissionSet: ["permissionSetId"],
  Policy: ["policyId"],
  PriceProvider: ["priceProviderId"],
  Prospect: ["prospectId"],
  Report: ["reportId"],
  ReportDefinition: ["reportDefinitionId"],
  ReportRun: ["reportRunId"],
  Role: ["roleId"],
  TermsTemplate: ["termsTemplateId"],
  TransactionTemplate: ["transactionTemplateId"],
  User: ["userId"],
  Wallet: ["walletId"],
  Withdrawal: ["withdrawalId"],
}
