#@ load("@ytt:data", "data")

#@ load("vendor/pipeline-fragments.lib.yml",
#@   "build_edge_image",
#@   "public_docker_registry",
#@   "nodejs_task_image_config",
#@   "rust_check_code",
#@   "docker_host_pool",
#@   "test_on_docker_host",
#@   "repo_resource",
#@   "edge_image_resource",
#@   "version_resource",
#@   "gh_release_resource",
#@   "pipeline_tasks_resource",
#@   "release_task_image_config",
#@   "rust_task_image_config",
#@   "charts_repo_resource",
#@   "charts_repo_bot_branch",
#@   "slack_resource_type",
#@   "slack_resource",
#@   "slack_failure_notification",
#@   "private_docker_registry"
#@ )

#@ load("app-template.lib.yml",
#@   "app_src_resource",
#@   "build_app_edge_image_name",
#@   "build_app_edge_image",
#@   "app_edge_image"
#@ )

#@ def on_nix_host(name, cmd):
#@ params = {}
#@ params["REPO_PATH"] = data.values.gh_repository
#@ params["GOOGLE_CREDENTIALS"] = "((staging-gcp-creds.creds_json))"
#@ params["SSH_PRIVATE_KEY"] = "((staging-ssh.ssh_private_key))"
#@ params["SSH_PUB_KEY"] = "((staging-ssh.ssh_public_key))"
#@ params["CMD"] = cmd
name: #@ name
serial: true
plan:
- { put: nix-host, params: { acquire: true } }
- in_parallel:
  - get: repo
    trigger: true
  - { get: pipeline-tasks }
- task: #@ name
  attempts: 2
  timeout: 18m
  tags: ["galoy-staging"]
  config:
    platform: linux
    image_resource: #@ rust_task_image_config()
    inputs:
    - name: pipeline-tasks
    - name: nix-host
    - name: repo
      path: #@ data.values.gh_repository
    params: #@ params
    run:
      path: pipeline-tasks/ci/tasks/run-on-nix-host.sh
  ensure:
    put: nix-host
    params:
      release: nix-host
#@ end

groups:
- name: lava-bank
  jobs:
  - check-code
  - integration-tests
  - bats-tests
  - build-edge-image
  - release
  - bump-image-in-chart
- name: admin-panel
  jobs:
  - #@ build_app_edge_image_name("admin-panel")

jobs:
- #@ rust_check_code()
- #@ on_nix_host("integration-tests", "make test-in-ci")
- #@ on_nix_host("bats-tests", "make e2e-in-ci")
- #@ build_edge_image()

- name: release
  serial: true
  plan:
  - in_parallel:
    - get: repo
      passed:
      - check-code
      - integration-tests
      - bats-tests
    - get: pipeline-tasks
    - get: version
    - get: edge-image
      passed: [build-edge-image]
      params:
        format: oci
  - task: prep-release
    config:
      platform: linux
      image_resource: #@ release_task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: repo
      - name: version
      outputs:
      - name: version
      - name: artifacts
      run:
        path: pipeline-tasks/ci/vendor/tasks/prep-release-src.sh
  - in_parallel:
    - task: build-osx-release
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            username: #@ data.values.osxcross_docker_username
            password: #@ data.values.osxcross_docker_password
            repository: #@ data.values.osxcross_repository
        inputs:
        - name: version
        - name: pipeline-tasks
        - name: repo
        outputs:
        - name: x86_64-apple-darwin
        caches:
        - path: cargo-home
        - path: cargo-target-dir
        params:
          TARGET: x86_64-apple-darwin
          OUT: x86_64-apple-darwin
        run:
          path: pipeline-tasks/ci/tasks/build-release.sh
    - task: build-static-release
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: clux/muslrust, tag: 1.78.0-stable }
        inputs:
        - name: version
        - name: pipeline-tasks
        - name: repo
        outputs:
        - name: x86_64-unknown-linux-musl
        caches:
        - path: cargo-home
        - path: cargo-target-dir
        params:
          TARGET: x86_64-unknown-linux-musl
          OUT: x86_64-unknown-linux-musl
        run:
          path: pipeline-tasks/ci/tasks/build-release.sh
  - put: repo
    params:
      tag: artifacts/gh-release-tag
      repository: repo
  - task: github-release
    config:
      image_resource: #@ rust_task_image_config()
      platform: linux
      inputs:
      - name: x86_64-apple-darwin
      - name: x86_64-unknown-linux-musl
      - name: version
      - name: pipeline-tasks
      - name: artifacts
      outputs:
      - name: artifacts
      params:
        BRANCH: #@ data.values.git_branch
      run:
        path: pipeline-tasks/ci/tasks/github-release.sh
  - put: latest-image
    params:
      image: edge-image/image.tar
      additional_tags: artifacts/gh-release-tag
  - put: gh-release
    params:
      name: artifacts/gh-release-name
      tag: artifacts/gh-release-tag
      body: artifacts/gh-release-notes.md
      globs: [artifacts/binaries/*]
  - put: version
    params:
      file: version/version

- name: bump-image-in-chart
  plan:
    - in_parallel:
        - get: edge-image
          passed: [ release ]
          params: { skip_download: true }
        - get: repo
          trigger: true
          passed: [ release ]
        - get: version
          trigger: true
          passed: [ release ]
        - get: charts-repo
          params: { skip_download: true }
        - get: pipeline-tasks
    - task: bump-image-digest-in-values
      config:
        platform: linux
        image_resource: #@ rust_task_image_config()
        inputs:
          - name: repo
          - name: edge-image
          - name: pipeline-tasks
          - name: charts-repo
          - name: version
        outputs:
          - name: charts-repo
        params:
          BRANCH: #@ data.values.git_charts_branch
          CHARTS_SUBDIR: lava-bank
        run:
          path: pipeline-tasks/ci/tasks/bump-image-digest.sh
    - put: charts-repo-bot-branch
      params:
        repository: charts-repo
        force: true
    - task: open-charts-pr
      config:
        platform: linux
        image_resource: #@ rust_task_image_config()
        inputs:
          - name: pipeline-tasks
          - name: edge-image
          - name: charts-repo
          - name: repo
        params:
          GH_APP_ID: #@ data.values.github_app_id
          GH_APP_PRIVATE_KEY: #@ data.values.github_app_private_key
          BRANCH: #@ data.values.git_charts_branch
          BOT_BRANCH: #@ data.values.git_charts_bot_branch
          CHARTS_SUBDIR: lava-bank
        run:
          path: pipeline-tasks/ci/tasks/chart-open-charts-pr.sh

- #@ build_app_edge_image("admin-panel")

resources:
- #@ repo_resource(True)
- #@ pipeline_tasks_resource()
- #@ slack_resource()
- #@ edge_image_resource(publicRepo=False)
- #@ version_resource()
- #@ gh_release_resource()
- #@ charts_repo_bot_branch()
- #@ charts_repo_resource()
- #@ app_src_resource("admin-panel")
- #@ app_edge_image("admin-panel")
- name: latest-image
  type: registry-image
  source:
    tag: latest
    username: #@ data.values.docker_registry_user
    password: #@ data.values.docker_registry_password
    repository: #@ private_docker_registry() + "/" + data.values.gh_repository
- name: nix-host
  type: pool
  source:
    uri: git@github.com:GaloyMoney/concourse-locks.git
    branch: main
    pool: docker-hosts
    private_key: #@ data.values.github_private_key

resource_types:
- #@ slack_resource_type()
