mutation approveLoan($loanId: UUID!, $collateral: Satoshis!, $principal: UsdCents!) {
  fixedTermLoanApprove(input: {
    loanId: $loanId
    collateral: $collateral
    principal: $principal
  }) {
    loan {
      loanId
      balance {
        collateral {
          btcBalance
        }
        outstanding {
          usdBalance
        }
        interestIncurred {
          usdBalance
        }
      }
    }
  }
}

{
  "loanId": "945773e8-738b-4229-a5da-390d87001001",
  "collateral": 100,
  "principal": 1000
}
