query FixedTermLoanBalance(
  $journalId: UUID!
  $collateralId: UUID!
  $loanOutstandingId: UUID!
  $interestIncomeId: UUID!
) {
  collateral: balance(
    journalId: $journalId
    accountId: $collateralId
    currency: "BTC"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  loanOutstanding: balance(
    journalId: $journalId
    accountId: $loanOutstandingId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  interestIncome: balance(
    journalId: $journalId
    accountId: $interestIncomeId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
}

{
  "journalId": "00000000-0000-0000-0000-000000000001",
  "collateralId": "eac052c2-c4e6-46e9-a6dc-9bdd82af0c49",
  "loanOutstandingId": "dd817f76-0b85-4688-b8cc-22060f57da77",
  "interestIncomeId": "f524fda7-ca7b-43c5-9a1d-fd977e76ec20"
}