mutation withdrawalInitiate(
  $userId: UUID!
) {
  withdrawalInitiate(input: {
    userId: $userId,
    amount: 1000000,
    destination: "some-address"
    reference: "withdrawal-01"
  
  }) {
    withdrawal {
      withdrawalId
      userId
    }
  }
}

{
  "input": {
    "userId": "df449512-e399-4471-a8e0-afa2a4f670ba",
    "amount": 10000,
    "destination": {
      "address": "tron-address"
    },
    "reference": "initiate_withdraw-01"
  }
}

withdrawId: "c4c00a50-b9c4-48eb-8a6f-4889fe131c67"
