mutation WithdrawalSettle(
  $withdrawalId: UUID!
) {
  withdrawalSettle(input: {
    withdrawalId: $withdrawalId
    reference: "settle_withdraw-01"
  }) {
    withdrawal {
      withdrawalId
      userId
    }
  }
}

{
  "input": {
    "withdrawalId": "c4c00a50-b9c4-48eb-8a6f-4889fe131c67",
    "confirmation": {
      "txId": "tron-tx-id"
    },
    "reference": "settle_withdraw-01"
  }
}
