[package]
name = "lava-events"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
governance = { path = "../../core/governance" }
shared-primitives = { path = "../../core/shared-primitives" }

serde = { workspace = true }
serde_json = { workspace = true }
