[package]
name = "lava-events"
version = "0.2.36-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
governance = { path = "../../core/governance" }
core-user = { path = "../../core/user" }
core-money = { path = "../../core/money" }
outbox = { path = "../../lib/outbox" }
lava-ids = { path = "../ids" }

chrono = { workspace = true }
serde = { workspace = true }
