name: "setup-nix"

description: "Composite action to install Nix, configure Cachix, cache Cargo dependencies, and optionally authenticate to Google Cloud."

inputs:

runs:
  using: "composite"
  steps:
    - name: Install Nix CLI
      uses: DeterminateSystems/nix-installer-action@v12

    - name: Clean up old tools
      run: |
        sudo rm -rf /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /opt/hostedtoolcache/CodeQL
      shell: bash

    - name: Configure Cachix
      uses: cachix/cachix-action@v15
      with:
        name: lana
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Cache Cargo registry and builds
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-gha-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-gha-

    - name: Authenticate to Google Cloud
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      if: env.GOOGLE_CREDENTIALS != ''
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.GOOGLE_CREDENTIALS }} 