name: "setup-nix"

description: "Composite action to install Nix, configure Cachix, cache Cargo dependencies, and optionally authenticate to Google Cloud."

inputs:
  cachix_auth_token:
    description: "Cachix authentication token."
    required: true
  google_credentials:
    description: "Google Cloud service account credentials JSON."
    required: false

runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@v16
    - run: |
        sudo rm -rf /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /opt/hostedtoolcache/CodeQL
      shell: bash
    - uses: cachix/cachix-action@v15
      with:
        name: lana
        authToken: ${{ inputs.cachix_auth_token }}

    - run: nix flake check
      shell: bash

    - name: Authenticate to Google Cloud
      env:
        GOOGLE_CREDENTIALS: ${{ inputs.google_credentials }}
      if: inputs.google_credentials != ''
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.google_credentials }} 