query ChartOfAccounts($accountSetId: UUID!) {
  accountSet(id: $accountSetId) {
    ...accountSetDetails
    categories: members(first: 10) {
      edges {
        node {
          __typename
          ... on AccountSet {
            ...accountSetDetails
            categoryAccounts: members(first: 25, after: null) {
              ...categoryAccount
            }
          }
          ... on Account {
            ...accountDetails
          }
        }
      }
    }
  }
}

query ChartOfAccountsCategoryAccount(
  $accountSetId: UUID!
  $first: Int!
  $after: String
) {
  accountSet(id: $accountSetId) {
    ...accountSetDetails
    categorySubAccounts: members(first: $first, after: $after) {
      ...subAccount
    }
  }
}

fragment accountSetDetails on AccountSet {
  accountSetId
  name
  normalBalanceType
  members(first: 1) {
    pageInfo {
      startCursor
    }
  }
}

fragment categoryAccount on AccountSetMemberConnection {
  pageInfo {
    startCursor
    endCursor
    hasNextPage
  }
  edges {
    cursor
    node {
      __typename
      ... on AccountSet {
        ...categorySubAccountSet
      }
      ... on Account {
        ...accountDetails
      }
    }
  }
}

fragment categorySubAccountSet on AccountSet {
  ...accountSetDetails
  categorySubAccounts: members(first: 1) {
    ...subAccount
  }
}

fragment accountDetails on Account {
  accountId
  code
  name
  normalBalanceType
}

fragment subAccount on AccountSetMemberConnection {
  pageInfo {
    startCursor
    endCursor
    hasNextPage
  }
  edges {
    cursor
    node {
      __typename
      ... on AccountSet {
        ...accountSetDetails
      }
      ... on Account {
        ...accountDetails
      }
    }
  }
}
