mutation CreateCustomerAccounts(
  $onBalanceSheetAccountId: UUID!
  $onBalanceSheetAccountCode: String!
  $onBalanceSheetAccountName: String!
  $customerCheckingControlAccountSetId: UUID!
  $tronAccountId: UUID!
  $tronAccountCode: String!
  $tronAccountName: String!
) {
  onBalanceSheet: accountCreate(
    input: {
      accountId: $onBalanceSheetAccountId
      code: $onBalanceSheetAccountCode
      name: $onBalanceSheetAccountName
      accountSetIds: [$customerCheckingControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  tron_address: bitfinex {
    addressBackedAccountCreate(
      input: {
        integrationId: "00000000-0000-0000-0000-200000000000"
        accountId: $tronAccountId
        code: $tronAccountCode
        type: "TRX"
        name: $tronAccountName
        depositCreditAccountId: $onBalanceSheetAccountId
      }
    ) {
      account {
        address
        account {
          accountId
        }
      }
    }
  }
}
