query LoanBalance(
  $journalId: UUID!
  $collateralId: UUID!
  $loanReceivableId: UUID!
  $interestIncomeId: UUID!
) {
  collateral: balance(
    journalId: $journalId
    accountId: $collateralId
    currency: "BTC"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  loanOutstanding: balance(
    journalId: $journalId
    accountId: $loanReceivableId
    currency: "USDT"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  interestIncome: balance(
    journalId: $journalId
    accountId: $interestIncomeId
    currency: "USDT"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
}
