mutation CreateLoanAccounts(
  $loanCollateralAccountId: UUID!
  $loanCollateralAccountCode: String!
  $loanCollateralAccountName: String!
  $loansCollateralControlAccountSetId: UUID!
  $loanReceivableAccountId: UUID!
  $loanReceivableAccountCode: String!
  $loanReceivableAccountName: String!
  $interestAccountId: UUID!
  $interestAccountCode: String!
  $interestAccountName: String!
  $loansAccountSetId: UUID!
  $loansReceivableControlAccountSetId: UUID!
  $interestRevenueAccountSetId: UUID!
  $interestRevenueControlAccountSetId: UUID!
) {
  collateral: accountCreate(
    input: {
      accountId: $loanCollateralAccountId
      code: $loanCollateralAccountCode
      name: $loanCollateralAccountName
      accountSetIds: [$loansCollateralControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  loansReceivable: accountCreate(
    input: {
      accountId: $loanReceivableAccountId
      code: $loanReceivableAccountCode
      name: $loanReceivableAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$loansAccountSetId, $loansReceivableControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  interest: accountCreate(
    input: {
      accountId: $interestAccountId
      code: $interestAccountCode
      name: $interestAccountName
      accountSetIds: [
        $interestRevenueAccountSetId
        $interestRevenueControlAccountSetId
      ]
    }
  ) {
    account {
      accountId
    }
  }
}
