[project]
name = "generate-es-reports"
version = "0.1.0"
description = "Meltano utility plugin to generate regulatory reports and upload to GCS"
readme = "README.md"
authors = [{ name = "Jose Rojas Echenique", email = "jir@galoy.io" }]
keywords = [
    "ELT",
    "BigQuery",
    "GCS",
    "Reporting",
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
license = "Apache-2.0"
license-files = [ "LICENSE" ]
requires-python = ">=3.8"
dynamic = ["dependencies"]

[tool.poetry]

[tool.poetry.dependencies]
google-cloud-bigquery = ">=3.0.0,<4.0.0"
google-cloud-storage = ">=2.0.0,<3.0.0"
dicttoxml = ">=1.7.0,<2.1.0"

[build-system]
requires = ["poetry-core>=2,<3"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
generate-reports = "generate-reports:main"
