[book]
language = "en"
src = "src"
title = "Lana Bank Documentation"

[build]
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]