query AccountingBaseConfig {
  chartOfAccounts {
    accountingBaseConfig {
      assetsCode
      liabilitiesCode
      equityCode
      equityRetainedEarningsGainCode
      equityRetainedEarningsLossCode
      revenueCode
      costOfRevenueCode
      expensesCode
      contingentObligationsCode,
      contingentRightsCode,
      memorandumCode,
    }
  }
}
