query AccountEntryCsv($ledgerAccountId: UUID!) {
  accountEntryCsv(ledgerAccountId: $ledgerAccountId) {
    id
    accountingCsvDocumentId
    ledgerAccountId
    status
    createdAt
    filename
  }
}
