query AuditLogs($first: Int!, $after: String, $action: String) {
  audit(first: $first, after: $after, action: $action) {
    edges {
      cursor
      node {
        id
        subject {
          ... on User {
            userId
            email
          }
          ... on System {
            actor
          }
        }
        object
        action
        authorized
        recordedAt
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
