query ChartOfAccounts {
  chartOfAccounts {
    chartId
    name
    lastMonthlyClosedAt
    children {
      ...child
      children {
        ...child
        children {
         ...child
          children {
            ...child
          }
        }
      }
    }
  }
}

fragment child on ChartNode {
  name
  accountCode
}
