mutation ChartOfAccountsCsvImportWithBaseConfig($input: ChartOfAccountsCsvImportWithBaseConfigInput!) {
  chartOfAccountsCsvImportWithBaseConfig(input: $input) {
    chartOfAccounts {
      chartId
    }
  }
}