query ChartOfAccountsAccountSet($accountSetId: UUID!) {
  chartOfAccountsAccountSet(accountSetId: $accountSetId) {
    name
    subAccounts(first: 10) {
      edges {
        cursor
        node {
          __typename
          ... on AccountDetails {
            __typename
            id
            name
          }
          ... on AccountSetDetails {
            __typename
            id
            name
            hasSubAccounts
          }
        }
      }
    }
  }
}
