query ChartOfAccount {
  chartOfAccounts {
    name
    categories {
      id
      name
      accounts(first: 5) {
        ... on ChartOfAccountsCategoryAccountSet {
          __typename
          queryableId: id
          name
          hasSubAccounts
        }
        ... on AccountDetails {
          __typename
          id
          name
        }
      }
    }
  }
}
