mutation WithdrawalConfirm($input: WithdrawalConfirmInput!) {
  withdrawalConfirm(input: $input) {
    withdrawal {
      withdrawalId
      status
      depositAccount {
        balance {
          settled
          pending
        }
      }
    }
  }
}
