mutation CreditFacilityProposalCustomerApprovalConclude(
  $input: CreditFacilityProposalCustomerApprovalConcludeInput!
) {
  creditFacilityProposalCustomerApprovalConclude(input: $input) {
    creditFacilityProposal {
      creditFacilityProposalId
    }
  }
}
