mutation creditFacilityPartialPaymentRecord(
  $input: CreditFacilityPartialPaymentRecordInput!
) {
  creditFacilityPartialPaymentRecord(input: $input) {
    creditFacility {
      creditFacilityId
      facilityAmount
      balance {
        facilityRemaining
        outstanding
        collateral
        disbursed {
          total
          outstanding
        }
        interest {
          total
          outstanding
        }
        paymentsUnapplied
      }
    }
  }
}
