mutation CreditFacilityAgreementDownloadLinkGenerate($input: CreditFacilityAgreementDownloadLinksGenerateInput!) {
  creditFacilityAgreementDownloadLinkGenerate(input: $input) {
    creditFacilityAgreementId
    link
  }
}