mutation CreditFacilityAgreementGenerate($input: CreditFacilityAgreementGenerateInput!) {
  creditFacilityAgreementGenerate(input: $input) {
    creditFacilityAgreement {
      creditFacilityAgreementId
      status
      createdAt
    }
  }
}