mutation CustomerDocumentArchive($input: CustomerDocumentArchiveInput!) {
  customerDocumentArchive(input: $input) {
    customerDocument {
      customerDocumentId
      customerId
      filename
      status
    }
  }
}
