query CustomerDocuments($customerId: CustomerId!) {
  customer(id: $customerId) {
    customerId
    email
    documents {
      customerDocumentId
      customerId
      filename
      status
    }
  }
}
