mutation customerDocumentAttach($file: Upload!, $customerId: String!) {
  customerDocumentAttach(input: { file: $file, customerId: $customerId }) {
    document {
      customerDocumentId
      customerId
      filename
    }
  }
}
