mutation DepositAccountFreeze($input: DepositAccountFreezeInput!) {
  depositAccountFreeze(input: $input) {
    account {
      depositAccountId
      status
      balance {
        settled
      }
    }
  }
}
