mutation DepositAccountClose($input: DepositAccountCloseInput!) {
  depositAccountClose(input: $input) {
    account {
      depositAccountId
      status
      balance {
        settled
      }
    }
  }
}
