mutation DepositAccountUnfreeze($input: DepositAccountUnfreezeInput!) {
  depositAccountUnfreeze(input: $input) {
    account {
      depositAccountId
      status
      balance {
        settled
      }
    }
  }
}
