query depositAccountConfig {
  depositAccountConfig {
    chartOfAccountsOmnibusParentCode
    chartOfAccountsIndividualDepositAccountsParentCode
    chartOfAccountsGovernmentEntityDepositAccountsParentCode
    chartOfAccountsPrivateCompanyDepositAccountsParentCode
    chartOfAccountsBankDepositAccountsParentCode
    chartOfAccountsFinancialInstitutionDepositAccountsParentCode
    chartOfAccountsNonDomiciledCompanyDepositAccountsParentCode
    chartOfAccountsFrozenIndividualDepositAccountsParentCode
    chartOfAccountsFrozenGovernmentEntityDepositAccountsParentCode
    chartOfAccountsFrozenPrivateCompanyDepositAccountsParentCode
    chartOfAccountsFrozenBankDepositAccountsParentCode
    chartOfAccountsFrozenFinancialInstitutionDepositAccountsParentCode
    chartOfAccountsFrozenNonDomiciledCompanyDepositAccountsParentCode
  }
}
