query creditFacility($id: UUID!) {
  creditFacility(id: $id) {
    creditFacilityId
    status
    maturesAt
    collateralizationState
    facilityAmount
    disbursals {
      id
      status
    }
    history {
      __typename
      ... on CreditFacilityInterestAccrued {
        cents
        recordedAt
        txId
        days
      }
      ... on CreditFacilityCollateralizationUpdated {
        state
      }
    }
    balance {
      facilityRemaining {
        usdBalance
      }
      outstanding {
        usdBalance
      }
      collateral {
        btcBalance
      }
      disbursed {
        total {
          usdBalance
        }
        outstanding {
          usdBalance
        }
      }
      interest {
        total {
          usdBalance
        }
        outstanding {
          usdBalance
        }
      }
      paymentsUnapplied {
        usdBalance
      }
    }
    liquidations {
      liquidationId
      collateralId
    }
  }
}
