query creditFacility($id: UUID!) {
  creditFacility(id: $id) {
    creditFacilityId
    collateralId
    status
    maturesAt
    collateralizationState
    facilityAmount
    disbursals {
      creditFacilityDisbursalId
      status
    }
    history {
      __typename
      ... on CreditFacilityInterestAccrued {
        cents
        recordedAt
        txId
        days
      }
      ... on CreditFacilityCollateralizationUpdated {
        state
      }
    }
    balance {
      facilityRemaining
      outstanding
      collateral
      disbursed {
        total
        outstanding
      }
      interest {
        total
        outstanding
      }
      paymentsUnapplied
    }
    liquidations {
      liquidationId
    }
  }
}
