query pendingCreditFacility($id: UUID!) {
  pendingCreditFacility(id: $id) {
    pendingCreditFacilityId
    collateralId
    status
    wallet {
      address
    }
    collateral {
      btcBalance
    }
  }
}
