query LatestFiscalYear($chartId: UUID!) {
    latestFiscalYear(chartId: $chartId) {
        id
        chartId
        firstPeriodOpenedAt
        firstPeriodOpenedAsOf
        lastMonthClosedAt
    }
}