mutation FiscalYearClose($input: FiscalYearCloseInput!) {
    fiscalYearClose(input: $input) {
        fiscalYear {
            id
            fiscalYearId
            openedAsOf
            closedAsOf
        }
    }
}