mutation FiscalYearCloseAndOpenNext($input: FiscalYearCloseAndOpenNextInput!) {
    fiscalYearCloseAndOpenNext(input: $input) {
        fiscalYear {
            id
            fiscalYearId
            openedAsOf
            closedAsOf
        }
    }
}