query FiscalYears($first: Int!, $after: String) {
    fiscalYears(first: $first, after: $after) {
        edges {
            cursor
            node {
                fiscalYearId
                openedAsOf
            }
        }
        nodes {
            fiscalYearId
            openedAsOf
            monthClosures {
                closedAsOf
                closedAt
            }
            isLastMonthOfYearClosed
            isOpen
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}