mutation FiscalYearModuleConfigure($input: FiscalYearModuleConfigureInput!) {
  fiscalYearModuleConfigure(input: $input) {
    fiscalYearConfig {
      yearEndMonth
      revenueCode
      costOfRevenueCode
      expensesCode
      equityRetainedEarningsCode
      equityRetainedLossesCode
    }
  }
}