mutation fiscalYearClose($input: FiscalYearCloseInput!) {
  fiscalYearClose(input: $input) {
    fiscalYear {
      id
      fiscalYearId
      chartId
      isOpen
      openedAsOf
      closedAsOf
      monthClosures {
        closedAsOf
        closedAt
      }
      isLastMonthOfYearClosed
    }
  }
}
