query FiscalYears($first: Int!, $after: String) {
    fiscalYears(first: $first, after: $after) {
        edges {
            cursor
            node {
                id
                fiscalYearId
                openedAsOf
            }
        }
        nodes {
            id
            fiscalYearId
            openedAsOf
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}