mutation WithdrawalInitiate($input: WithdrawalInitiateInput!) {
  withdrawalInitiate(input: $input) {
    withdrawal {
      withdrawalId
      approvalProcessId
      status
      account {
        status
        balance {
          settled
          pending
        }
      }
    }
  }
}
