query LedgerAccountCsv($ledgerAccountId: UUID!) {
  ledgerAccountCsv(ledgerAccountId: $ledgerAccountId) {
    ledgerAccountCsvDocumentId
    ledgerAccountId
    status
    createdAt
    filename
  }
}
