mutation LedgerAccountCsvCreate($input: LedgerAccountCsvCreateInput!) {
  ledgerAccountCsvCreate(input: $input) {
    ledgerAccountCsvDocument {
      ledgerAccountCsvDocumentId
      ledgerAccountId
      status
      createdAt
      filename
    }
  }
}
