mutation LedgerAccountCsvDownloadLinkGenerate(
  $input: LedgerAccountCsvDownloadLinkGenerateInput!
) {
  ledgerAccountCsvDownloadLinkGenerate(input: $input) {
    link {
      url
      csvId
    }
  }
}
