mutation LedgerAccountCsvCreate($input: LedgerAccountCsvCreateInput!) {
  ledgerAccountCsvCreate(input: $input) {
    accountingCsvDocument {
      accountingCsvDocumentId
      ledgerAccountId
      status
      createdAt
      filename
    }
  }
}
