mutation LiquidationRecordCollateralSent($input: CollateralRecordSentToLiquidationInput!) {
  collateralRecordSentToLiquidation(input: $input) {
    collateral {
      collateralId
      creditFacility {
        liquidations {
          liquidationId
          sentTotal
          sentCollateral {
            amount
          }
        }
      }
    }
  }
}

