mutation LiquidationRecordProceedsReceived($input: LiquidationRecordProceedsReceivedInput!) {
  liquidationRecordProceedsReceived(input: $input) {
    liquidation {
      liquidationId
      amountReceived
      receivedProceeds {
        amount
      }
    }
  }
}


