mutation LiquidationRecordPaymentReceived($input: LiquidationRecordPaymentReceivedInput!) {
  liquidationRecordPaymentReceived(input: $input) {
    liquidation {
      liquidationId
      receivedTotal
      receivedPayment {
        amount
      }
    }
  }
}


