mutation CollateralRecordProceedsFromLiquidation($input: CollateralRecordProceedsFromLiquidationInput!) {
  collateralRecordProceedsFromLiquidation(input: $input) {
    collateral {
      collateralId
    }
  }
}
