mutation LiquidationRecordCollateralSent($input: LiquidationRecordCollateralSentInput!) {
  collateralLiquidationRecordCollateralSent(input: $input) {
    collateral {
      collateralId
      creditFacility {
        liquidations {
          liquidationId
          sentTotal
          sentCollateral {
            amount
          }
        }
      }
    }
  }
}

