mutation LoanAgreementGenerate($input: LoanAgreementGenerateInput!) {
  loanAgreementGenerate(input: $input) {
    loanAgreement {
      id
      loanAgreementId
      status
      createdAt
    }
  }
} 