mutation CreditFacilityAgreementGenerate($input: CreditFacilityAgreementGenerateInput!) {
  creditFacilityAgreementGenerate(input: $input) {
    loanAgreement {
      id
      loanAgreementId
      status
      createdAt
    }
  }
}