mutation ExecuteManualTransaction($input: LedgerManualTransactionExecuteInput!) {
  ledgerManualTransactionExecute(input: $input) {
    transaction {
      ledgerTransactionId
      createdAt
      effective
      description
      entries {
        ledgerEntryId
      }
    }
  }
}
