mutation NotificationEmailConfigUpdate($input: NotificationEmailConfigInput!) {
  notificationEmailConfigUpdate(input: $input) {
    notificationEmailConfig {
      fromEmail
      fromName
    }
  }
}
