mutation RecordDeposit($input: DepositRecordInput!) {
  depositRecord(input: $input) {
    deposit {
      depositId
      amount
      depositAccount {
        balance {
          settled
          pending
        }
      }
    }
  }
}
