query ReportRuns($first: Int!) {
  reportRuns(first: $first) {
    nodes {
      reportRunId
      state
      reports {
        reportId
        files {
          extension
        }
      }
    }
  }
}
