query TermsTemplateGet($id: UUID!) {
  termsTemplate(termsTemplateId: $id) {
    termsTemplateId
    name
    values {
      annualRate
      accrualCycleInterval
      duration {
        period
        units
      }
      liquidationCvl {
        ... on FiniteCvlPct {
          value
        }
        ... on InfiniteCvlPct {
          isInfinite
        }
      }
      marginCallCvl {
        ... on FiniteCvlPct {
          value
        }
        ... on InfiniteCvlPct {
          isInfinite
        }
      }
      initialCvl {
        ... on FiniteCvlPct {
          value
        }
        ... on InfiniteCvlPct {
          isInfinite
        }
      }
    }
  }
}
