mutation TermsTemplateUpdate($input: TermsTemplateUpdateInput!) {
  termsTemplateUpdate(input: $input) {
    termsTemplate {
      termsTemplateId
      name
      values {
        annualRate
        accrualCycleInterval
        duration {
          period
          units
        }
        liquidationCvl {
          ... on FiniteCvlPct {
            value
          }
          ... on InfiniteCvlPct {
            isInfinite
          }
        }
        marginCallCvl {
          ... on FiniteCvlPct {
            value
          }
          ... on InfiniteCvlPct {
            isInfinite
          }
        }
        initialCvl {
          ... on FiniteCvlPct {
            value
          }
          ... on InfiniteCvlPct {
            isInfinite
          }
        }
      }
    }
  }
}
