query TrialBalance($first: Int!, $after: String) {
  trialBalance(first: $first, after: $after) {
    name
    totalBalance {
      ...balancesByCurrency
    }
    lineItemBalances {
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      edges {
        cursor
        node {
          name
          totalBalance {
            ...balancesByCurrency
          }
        }
      }
    }
  }
}

fragment balancesByCurrency on AccountBalancesByCurrency {
  btc: btc {
    ...btcBalances
  }
  usd: usd {
    ...usdBalances
  }
  usdt: usdt {
    ...usdBalances
  }
}

fragment btcBalances on LayeredBtcAccountBalances {
  settled {
    net
    debit
    credit
  }
  pending {
    net
    debit
    credit
  }
  encumbrance {
    net
    debit
    credit
  }
}

fragment usdBalances on LayeredUsdAccountBalances {
  settled {
    net
    debit
    credit
  }
  pending {
    net
    debit
    credit
  }
  encumbrance {
    net
    debit
    credit
  }
}
