query TrialBalance($from: Timestamp!) {
  trialBalance(from: $from) {
    name
    balance {
      ...balancesByCurrency
    }
    subAccounts {
      ... on AccountWithBalance {
        name
        balance {
          ...balancesByCurrency
        }
      }
      ... on AccountSetWithBalance {
        name
        balance {
          ...balancesByCurrency
        }
      }
    }
  }
}

fragment balancesByCurrency on AccountBalancesByCurrency {
  btc: btc {
    ...rangedBtcBalances
  }
  usd: usd {
    ...rangedUsdBalances
  }
}

fragment rangedBtcBalances on RangedBtcAccountBalances {
  balancesByLayer: end {
    ...btcBalances
  }
}

fragment rangedUsdBalances on RangedUsdAccountBalances {
  balancesByLayer: end {
    ...usdBalances
  }
}

fragment btcBalances on LayeredBtcAccountBalances {
  all {
    ...btcLayers
  }
  settled {
    ...btcLayers
  }
  pending {
    ...btcLayers
  }
  encumbrance {
    ...btcLayers
  }
}

fragment usdBalances on LayeredUsdAccountBalances {
  all {
    ...usdLayers
  }
  settled {
    ...usdLayers
  }
  pending {
    ...usdLayers
  }
  encumbrance {
    ...usdLayers
  }
}

fragment usdLayers on UsdAccountBalance {
  netDebit
  debit
  credit
}

fragment btcLayers on BtcAccountBalance {
  netDebit
  debit
  credit
}
