mutation WithdrawalCancel($input: WithdrawalCancelInput!) {
  withdrawalCancel(input: $input) {
    withdrawal {
      withdrawalId
      status
      account {
        balance {
          settled
          pending
        }
      }
    }
  }
}
