[project]
name = "tap-bitfinexapi"
version = "0.0.1"
description = "Singer tap for BitfinexApi, built with the Meltano Singer SDK."
readme = "README.md"
requires-python = ">=3.9"
dynamic = ["dependencies"]

[tool.poetry]

[tool.poetry.dependencies]
singer-sdk = { version="~=0.43.1", extras = [] }
requests = "~=2.32.4"

[build-system]
requires = ["poetry-core>=2,<3"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-bitfinexapi = 'tap_bitfinexapi.tap:TapBitfinexApi.cli'
