name: "Podman BATS Tests"

on:
  pull_request:
    branches:
      - main
      - "feature/**"

env:
  ENGINE_DEFAULT: podman
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  TF_VAR_sa_creds: ${{ secrets.GOOGLE_SA_BASE64 }}
  SA_CREDS_BASE64: ${{ secrets.GOOGLE_SA_BASE64 }}
  SUMSUB_KEY: ${{ secrets.SUMSUB_KEY }}
  SUMSUB_SECRET: ${{ secrets.SUMSUB_SECRET }}
  TF_VAR_name_prefix: "gha"
  TARGET_BIGQUERY_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
  TARGET_BIGQUERY_DATASET: "gha_dataset"
  TARGET_BIGQUERY_LOCATION: "US"
  DBT_BIGQUERY_PROJECT: "dbt_gha"

jobs:
  bats-tests:
    name: End to End BATS Tests (Podman)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-podman

      - uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN_LANA_CI }}
          google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}

      - run: nix develop -c make reset-deps

      # - name: Run BATS tests with podman
      #   run: nix develop -c make e2e
      #
      # - name: Rename bats log
      #   if: always()
      #   run: mv .e2e-logs e2e-logs || true
      #
      # - name: Upload bats log
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Podman BATS Logs
      #     path: |
      #       e2e-logs
      #       *.e2e-logs

      - run: |
          echo $TARGET_BIGQUERY_CREDENTIALS_JSON > meltano/keyfile.json
          export DBT_BIGQUERY_KEYFILE="$(pwd)/meltano/keyfile.json"
          export DBT_BIGQUERY_PROJECT="$(echo $TF_VAR_sa_creds | base64 -d | jq -r '.project_id')"
          echo "DBT_BIGQUERY_KEYFILE=$DBT_BIGQUERY_KEYFILE" >> $GITHUB_ENV
          echo "DBT_BIGQUERY_PROJECT=$DBT_BIGQUERY_PROJECT" >> $GITHUB_ENV

      - run: nix develop -c meltano install
      - run: nix develop -c meltano run tap-postgres target-bigquery
      - run: nix develop -c meltano run tap-bitfinexapi target-bigquery
      - run: nix develop -c meltano run tap-sumsubapi target-bigquery
      - run: nix develop -c meltano run dbt-bigquery:run
      - run: nix develop -c meltano run generate-es-reports:run
