name: "E2E Tests"

on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  integration:
    name: End to End Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-gha-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-gha-
      - id: "gcp-auth"
        uses: "google-github-actions/auth@v2"
        if: secrets.GOOGLE_CREDENTIALS != ''
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - run: nix develop -c make e2e
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_sa_creds: ${{ secrets.GOOGLE_SA_BASE64 }}
          SA_CREDS_BASE64: ${{ secrets.GOOGLE_SA_BASE64 }}
          SUMSUB_KEY: ${{ secrets.SUMSUB_KEY }}
          SUMSUB_SECRET: ${{ secrets.SUMSUB_SECRET }}
          TF_VAR_name_prefix: "gha"
      - if: always()
        run: mv .e2e-logs e2e-logs
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Tilt log
          path: |
            e2e-logs
            *.e2e-logs
