name: "E2E Tests"

on:
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  integration:
    name: End to End Test
    runs-on: ubuntu-latest
    steps:
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: actions/checkout@v3
      - id: "gcp-auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - name: Run e2e tests
        run: nix develop -c make e2e
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_sa_creds: ${{ secrets.GOOGLE_SA_BASE64 }}
          SA_CREDS_BASE64: ${{ secrets.GOOGLE_SA_BASE64 }}
          SUMSUB_KEY: ${{ secrets.SUMSUB_KEY }}
          SUMSUB_SECRET: ${{ secrets.SUMSUB_SECRET }}
          TF_VAR_name_prefix: "gha"
      - name: Rename Tilt log
        if: always()
        run: mv .e2e-logs e2e-logs
      - name: Upload Tilt log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Tilt log
          path: |
            e2e-logs
            *.e2e-logs
