name: Update Dependency Caches

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow workflow to write cache
permissions:
  actions: write
  contents: read

jobs:
  update-pnpm-cache:
    name: Update PNPM Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN_LANA_CI }}
          # google_credentials not needed for caching/building

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: |
          echo "STORE_PATH=$(nix develop -c pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm dependencies
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache-dir.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install PNPM dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: nix develop -c pnpm install

  nix-build-cache:
    name: Update Nix Build Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN_LANA_CI }}
          google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: build
        run: nix build .
