name: Check Code Apps

on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  check-code-apps:
    name: Check Code Apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: cachix/cachix-action@v15
        with:
          name: lana-bank-ci
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - run: nix develop -c make check-code-apps
