#! Auto synced from Shared CI Resources repository
#! Don't change this file, instead change it in github.com/GaloyMoney/concourse-shared

name: Check Code

on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  check-code-backend:
    name: Check Code Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN_LANA_CI }}
          google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: ./.github/actions/cache-rust 
      - run: nix develop -c make check-code

  check-code-apps:
    name: Check Code Apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN_LANA_CI }}
          google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: ./.github/actions/cache-pnpm
      - run: nix develop -c make check-code-apps

  fmt:
    name: Check terraform files formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - run: terraform fmt -recursive -check 
