#! Auto synced from Shared CI Resources repository
#! Don't change this file, instead change it in github.com/GaloyMoney/concourse-shared

name: Check Code

on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  check-code-backend:
    name: Check Code Backend
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-gha-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-gha-
      - run: nix develop --max-jobs 0 -c make check-code

  check-code-apps:
    name: Check Code Apps
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: actions/checkout@v4
      - run: nix develop --max-jobs 0 -c make check-code-apps
