name: cypress

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-test-run-in-browserstack:
    name: browserstack / local tunnel into tilt up
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: actions/checkout@v4

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: build backend
        run: nix develop -c make build-for-tests

      - name: sync dataform-branch
        run: nix develop -c make push-dataform-branch
        env:
          DATAFORM_BRANCH: "gha-dataform"

      - name: keep tilt running
        run: nix develop -c make tilt-in-ci
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_sa_creds: ${{ secrets.GOOGLE_SA_BASE64 }}
          SA_CREDS_BASE64: ${{ secrets.GOOGLE_SA_BASE64 }}
          SUMSUB_KEY: ${{ secrets.SUMSUB_KEY }}
          SUMSUB_SECRET: ${{ secrets.SUMSUB_SECRET }}
          TF_VAR_name_prefix: "gha"

      - name: system info
        run: |
          free -h
          df -h

      - name: run cypress tests
        run: nix develop -c make test-cypress-in-ci-through-browserstack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: upload cypress screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: apps/admin-panel/cypress/manuals/screenshots/*

  manual-generation:
    name: manual pdfs / upload to lana-manuals.netlify.app
    needs: cypress-test-run-in-browserstack
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: screenshots
          path: apps/admin-panel/cypress/manuals/screenshots/*
      - name: generate pdfs
        run: cd apps/admin-panel && nix develop -c pnpm run local:pdf
