on:
  pull_request:
    branches:
      - main

name: Nix flake check

jobs:
  fast-checks:
    name: Nix fast checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: cachix/cachix-action@v15
        with:
          name: galoymoney
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true

      - run: nix build .#checks.x86_64-linux.fast --no-link

  rust-checks:
    name: Nix Rust checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: cachix/cachix-action@v15
        with:
          name: galoymoney
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build .#checks.x86_64-linux.rust --no-link
