name: Check terraform files formatting
on:
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code into workspace directory
      uses: actions/checkout@v4
    - name: Terraform fmt
      uses: hashicorp/setup-terraform@v3
    - run: terraform fmt -recursive .
    - run: git diff --exit-code
