name: Cypress Tests

on:
  pull_request:
    branches: [main]

jobs:
  tilt-ci:
    name: Tilt CI
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tilt CI
        run: nix develop -c make tilt-ci
