name: "Rust integration"

on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup-podman
      
      - uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN_LANA_CI }}
          google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          
      - name: Run integration tests with podman
        run: nix develop -c make test-in-ci-cargo
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SA_CREDS_BASE64: ${{ secrets.GOOGLE_SA_BASE64 }}
          TF_VAR_name_prefix: "gha" 