name: Facility Scenarios

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  simulations:
    name: Simulations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN_LANA_CI }}
          google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Start server with logs
        run: |
          nohup nix develop -c make reset-deps setup-db run-server-with-bootstrap \
            2>&1 | tee server.log &
          echo "PID=$!" > .server.pid

      - name: Wait for healthy server
        run: |
          nix develop -c wait4x http http://localhost:5253/health --timeout 15m
          
      - name: Check no panics
        run: |
          if grep -q "panicked" server.log; then
            echo "❌ Server panicked; dumping last 200 lines of logs:"
            tail -n 200 server.log
            cat .server.pid | xargs kill || true
            exit 1
          fi
