name: Storybook

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
    paths:
      - "apps/admin-panel/**"
  push:
    branches: [main]
    paths:
      - "apps/admin-panel/**"

jobs:
  storybook-preview:
    name: Storybook Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: ./.github/actions/cache-pnpm
      - run: nix develop -c make build-storybook-admin-panel
      - id: netlify_deploy
        if: github.event_name == 'pull_request'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 8f3d8282-da53-4b6d-8d3c-708c7d7030c9
        run: |
          GITHUB_SHA="${{ github.sha }}"
          SHORT_SHA="${GITHUB_SHA::7}"
          ALIAS="pr-${{ github.event.pull_request.number }}-commit-${SHORT_SHA}"
          nix develop -c netlify deploy \
            --dir=apps/admin-panel/storybook-static \
            --filter=admin-panel \
            --site=$NETLIFY_SITE_ID \
            --auth=$NETLIFY_AUTH_TOKEN \
            --alias="$ALIAS" \
            --message="Storybook Preview for PR #${{ github.event.pull_request.number }} Commit $GITHUB_SHA" \
            --json > deploy-info.json
          DEPLOY_URL=$(jq -r '.deploy_url' deploy-info.json)
          echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
      - if: github.event_name == 'push'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 8f3d8282-da53-4b6d-8d3c-708c7d7030c9
        run: |
          nix develop -c netlify deploy \
            --prod \
            --dir=apps/admin-panel/storybook-static \
            --filter=admin-panel \
            --site=$NETLIFY_SITE_ID \
            --auth=$NETLIFY_AUTH_TOKEN \
            --message="Storybook Build for Commit ${{ github.sha }}" \
            --json > deploy-info.json
          DEPLOY_URL=$(jq -r '.deploy_url' deploy-info.json)
          echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
      - if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const deployUrl = '${{ steps.netlify_deploy.outputs.deploy_url }}';
            const commentBody = `<!-- Storybook Preview Comment -->\nStorybook preview: [Link to Storybook](${deployUrl})`;

            // Fetch existing comments on the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            // Identify if the bot has already made a comment
            const botLogin = 'github-actions[bot]'
            const existingComment = comments.find(
              comment => comment.user.login === botLogin && comment.body.includes('<!-- Storybook Preview Comment -->')
            );

            if (existingComment) {
              // Update the existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody,
              });
            } else {
              // Create a new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody,
              });
            }
