name: "Test Podman Setup"

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  test-podman:
    name: Test Podman Installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup-podman
      
      - name: Test podman functionality
        run: |
          echo "--- Testing podman basic functionality ---"
          podman version
          podman info
          
          echo "--- Testing container pull and run ---"
          podman pull alpine:latest
          podman run --rm alpine:latest echo "Hello from podman!"
          
          echo "--- Testing docker-compose compatibility ---"
          echo "version: '3.8'
          services:
            test:
              image: alpine:latest
              command: echo 'Hello from podman-compose!'" > test-compose.yml
          
          DOCKER_HOST=$(./dev/bin/podman-get-socket.sh) podman-compose -f test-compose.yml up --abort-on-container-exit
          
          echo "--- Podman setup test complete ---" 