name: "Integration Tests"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - uses: actions/checkout@v3
      - name: Run integration tests
        run: nix develop -c make test-in-ci

