name: "Integration Tests"

on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-gha-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-gha-
      - id: "gcp-auth"
        uses: "google-github-actions/auth@v2"
        if: secrets.GOOGLE_CREDENTIALS != ''
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -c make test-in-ci
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SA_CREDS_BASE64: ${{ secrets.GOOGLE_SA_BASE64 }}
          TF_VAR_name_prefix: "gha"
