name: "Tilt CI"
on:
  pull_request:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - id: "gcp-auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
    - name: Setup container monitoring
      run: |
        mkdir -p ./logs
        # Log docker stats every 5 seconds with timestamp
        (while true; do 
          echo "$(date '+%Y-%m-%d %H:%M:%S')" >> ./logs/container_memory.log
          docker stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}" >> ./logs/container_memory.log
          echo "---" >> ./logs/container_memory.log
          sleep 5
        done) &
        echo $! > monitor.pid:
    - name: Reset Deps
      run: nix develop -c make reset-deps
    - name: Tilt CI
      run: nix develop -c make tilt-in-ci
      env:
        TF_VAR_sa_creds: ${{ secrets.GOOGLE_SA_BASE64 }}
        # Add these two steps:
    - name: Stop monitoring
      if: always()  # Run even if previous steps failed
      run: |
        if [ -f monitor.pid ]; then
          kill $(cat monitor.pid)
        fi
        
    - name: Upload memory logs
      if: always()  # Run even if previous steps failed
      uses: actions/upload-artifact@v3
      with:
        name: memory-logs
        path: |
          ./logs/container_memory.log
          ~/.tilt-dev/logs  # Include Tilt logs as well
